Appease... shfmt!

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -2,20 +2,21 @@
 set -eo pipefail
 
 ASDF_INSTALL_TYPE=${ASDF_INSTALL_TYPE:-version  }
-[ -n "$ASDF_INSTALL_PATH" ] || (>&2 echo 'Missing ASDF_INSTALL_PATH' && exit 1)
-[ -n "$ASDF_INSTALL_VERSION" ] || (>&2 echo 'Missing ASDF_INSTALL_VERSION' && exit 1)
+[ -n "$ASDF_INSTALL_PATH" ] || (echo >&2 'Missing ASDF_INSTALL_PATH' && exit 1)
+[ -n "$ASDF_INSTALL_VERSION" ] || (echo >&2 'Missing ASDF_INSTALL_VERSION' && exit 1)
 
 _get_arch() {
-  local arch; arch=$(uname -m)
-  case $arch in
-    armv*) arch="arm";;
-    aarch64) arch="arm64";;
-    x86) arch="386";;
-    x86_64) arch="amd64";;
-    i686) arch="386";;
-    i386) arch="386";;
-  esac
-  echo "$arch"
+	local arch
+	arch=$(uname -m)
+	case $arch in
+	armv*) arch="arm" ;;
+	aarch64) arch="arm64" ;;
+	x86) arch="386" ;;
+	x86_64) arch="amd64" ;;
+	i686) arch="386" ;;
+	i386) arch="386" ;;
+	esac
+	echo "$arch"
 }
 
 _get_platform() {
