One-liner for ENV var check
Based on asdf-bat
https://gitlab.com/wt0f/asdf-bat/-/blob/master/bin/install

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -2,16 +2,8 @@
 set -eo pipefail
 
 ASDF_INSTALL_TYPE=${ASDF_INSTALL_TYPE:-version  }
-
-test -n "$ASDF_INSTALL_VERSION" || {
-	echo 'Missing ASDF_INSTALL_VERSION'
-	exit 1
-}
-
-test -n "$ASDF_INSTALL_PATH" || {
-	echo 'Missing ASDF_INSTALL_PATH'
-	exit 1
-}
+[ -n "$ASDF_INSTALL_PATH" ] || (>&2 echo 'Missing ASDF_INSTALL_PATH' && exit 1)
+[ -n "$ASDF_INSTALL_VERSION" ] || (>&2 echo 'Missing ASDF_INSTALL_VERSION' && exit 1)
 
 _get_arch() {
   local arch; arch=$(uname -m)
